#!/usr/bin/env bash
set -Eeuo pipefail

DEPLOY_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
USER_ENV="$DEPLOY_DIR/.env"
GENERATED_DIR="$DEPLOY_DIR/.generated"
RUNTIME_ENV="$GENERATED_DIR/runtime.env"
COMPOSE_FILE="$DEPLOY_DIR/docker-compose.yml"

cd "$DEPLOY_DIR"
umask 077

die() {
  printf 'Error: %s\n' "$*" >&2
  exit 1
}

require_command() {
  command -v "$1" >/dev/null 2>&1 || die "$1 is required"
}

load_env() {
  [ -f "$USER_ENV" ] || die "missing $USER_ENV; run bash ./deploy.sh init first"
  set -a
  # shellcheck disable=SC1090
  source "$USER_ENV"
  if [ -f "$RUNTIME_ENV" ]; then
    # shellcheck disable=SC1090
    source "$RUNTIME_ENV"
  fi
  set +a
}

random_hex() {
  openssl rand -hex "$1"
}

existing_or_random() {
  local name="$1"
  local bytes="$2"
  local value="${!name:-}"
  if [ -z "$value" ]; then
    value="$(random_hex "$bytes")"
  fi
  printf '%s=%s\n' "$name" "$value"
}

init_config() {
  require_command openssl
  if [ ! -f "$USER_ENV" ]; then
    cp "$DEPLOY_DIR/.env.example" "$USER_ENV"
    chmod 600 "$USER_ENV"
    printf 'Created %s. Set PUBLIC_ORIGIN before installing.\n' "$USER_ENV"
  fi
  mkdir -p "$GENERATED_DIR"
  chmod 700 "$GENERATED_DIR"
  load_env

  local tmp="$RUNTIME_ENV.tmp"
  {
    printf '# Generated by deploy.sh. Do not edit.\n'
    existing_or_random POSTGRES_PASSWORD 24
    existing_or_random OCTOPUS_DB_PASSWORD 24
    existing_or_random SEPIIDA_DB_PASSWORD 24
    existing_or_random OCTOPUS_JWT_SECRET 32
    existing_or_random DEFAULT_ADMIN_PASSWORD 18
    existing_or_random SEPIIDA_QUERY_KEY 32
    existing_or_random SEPIIDA_AGENT_KEY 32
  } >"$tmp"
  mv "$tmp" "$RUNTIME_ENV"
  chmod 600 "$RUNTIME_ENV"

  # shellcheck disable=SC1090
  source "$RUNTIME_ENV"
  printf '%s\n' "$SEPIIDA_QUERY_KEY" >"$GENERATED_DIR/sepiida-query-keys.txt"
  printf '%s\n' "$SEPIIDA_AGENT_KEY" >"$GENERATED_DIR/sepiida-agent-keys.txt"
  chmod 600 "$GENERATED_DIR/sepiida-query-keys.txt" "$GENERATED_DIR/sepiida-agent-keys.txt"
  printf 'Self-hosted configuration initialized.\n'
}

resolve_paths() {
  WORKFLOW_HOST_DIR="$(realpath "${WORKFLOW_HOST_DIR:-$DEPLOY_DIR/workflows}")"
  INSTALL_ROOT="${INSTALL_ROOT:-/opt/schemabio}"
  DATA_ROOT="${DATA_ROOT:-/var/lib/schemabio}"
  if [ -z "${MINIWDL_PATH:-}" ]; then
    MINIWDL_PATH="$(command -v miniwdl || true)"
  fi
  export WORKFLOW_HOST_DIR INSTALL_ROOT DATA_ROOT MINIWDL_PATH
}

check_config() {
  require_command docker
  require_command openssl
  require_command realpath
  docker compose version >/dev/null 2>&1 || die "Docker Compose v2 is required"
  load_env

  [[ "${PUBLIC_ORIGIN:-}" =~ ^https://[^/@?#[:space:]]+$ ]] || die "PUBLIC_ORIGIN must be an https origin without credentials, path, query, fragment, or trailing slash"
  case "$PUBLIC_ORIGIN" in
    *example.com*) die "PUBLIC_ORIGIN still contains a placeholder" ;;
  esac

  resolve_paths
  [[ "$INSTALL_ROOT" = /* ]] || die "INSTALL_ROOT must be an absolute path"
  [[ "$DATA_ROOT" = /* ]] || die "DATA_ROOT must be an absolute path"
  [[ "$MINIWDL_PATH" = /* ]] || die "MINIWDL_PATH must resolve to an absolute path"
  [ -d "$WORKFLOW_HOST_DIR" ] || die "WORKFLOW_HOST_DIR does not exist"
  [ -f "$WORKFLOW_HOST_DIR/conf/local.cfg" ] || die "WORKFLOW_HOST_DIR/conf/local.cfg is required"
  [ -n "$MINIWDL_PATH" ] || die "miniwdl was not found; set MINIWDL_PATH"
  [ -x "$MINIWDL_PATH" ] || die "MINIWDL_PATH is not executable"
  [ -f "$RUNTIME_ENV" ] || die "runtime secrets are missing; run bash ./deploy.sh init"
  if [ "$(uname -s)" = "Linux" ]; then
    [ "$(stat -c %a "$RUNTIME_ENV")" = "600" ] || die "runtime secrets file must have mode 0600"
  fi
  [ "${#OCTOPUS_JWT_SECRET}" -ge 32 ] || die "generated OCTOPUS_JWT_SECRET is too short"
  "$MINIWDL_PATH" --version >/dev/null

  local port
  for port in "${POSTGRES_PORT:-54320}" "${OCTOPUS_PORT:-8080}" "${SEPIIDA_PORT:-9090}" "${YIJIAN_PORT:-3000}"; do
    [[ "$port" =~ ^[0-9]+$ ]] && [ "$port" -ge 1 ] && [ "$port" -le 65535 ] || die "service ports must be integers from 1 to 65535"
  done

  docker compose --env-file "$USER_ENV" --env-file "$RUNTIME_ENV" -f "$COMPOSE_FILE" config --quiet
  printf 'Self-hosted configuration is valid.\n'
}

compose() {
  docker compose --env-file "$USER_ENV" --env-file "$RUNTIME_ENV" -f "$COMPOSE_FILE" "$@"
}

require_root() {
  [ "${EUID:-$(id -u)}" -eq 0 ] || die "this command must run as root"
}

extract_binary() {
  local image="$1"
  local source_path="$2"
  local destination="$3"
  local container_id
  container_id="$(docker create "$image")"
  if ! docker cp "$container_id:$source_path" "$destination"; then
    docker rm "$container_id" >/dev/null || true
    return 1
  fi
  docker rm "$container_id" >/dev/null
  chmod 0755 "$destination"
}

write_host_environment() {
  mkdir -p /etc/schemabio
  cat > /etc/schemabio/octopus.env <<EOF
SERVER_PORT=${OCTOPUS_PORT:-8080}
GIN_MODE=release
CORS_ALLOWED_ORIGINS=$PUBLIC_ORIGIN
DB_DRIVER=postgres
DB_DSN="host=127.0.0.1 user=octopus password=$OCTOPUS_DB_PASSWORD dbname=octopus port=${POSTGRES_PORT:-54320} sslmode=disable TimeZone=Asia/Shanghai"
OUTPUT_DIR=$DATA_ROOT/output
TEMPLATE_DIR=$WORKFLOW_HOST_DIR
ARCHIVE_DIR=$DATA_ROOT/archive
ARCHIVE_CLEANUP=${ARCHIVE_CLEANUP:-false}
DEFAULT_EXECUTOR=local
MINIWDL_PATH=$MINIWDL_PATH
STORAGE_PROVIDER=local
STORAGE_LOCAL_DIR=$DATA_ROOT/uploads
UPLOAD_MAX_SIZE_MB=${UPLOAD_MAX_SIZE_MB:-0}
DATA_RETENTION_DAYS=${DATA_RETENTION_DAYS:-0}
SEPIIDA_ENABLED=true
SEPIIDA_URL=http://127.0.0.1:${SEPIIDA_PORT:-9090}
SEPIIDA_QUERY_KEY=$SEPIIDA_QUERY_KEY
PARQUET_ENABLED=${PARQUET_ENABLED:-true}
JWT_SECRET=$OCTOPUS_JWT_SECRET
JWT_COOKIE_SECURE=true
CREATE_DEFAULT_ADMIN=true
DEFAULT_ADMIN_EMAIL=${DEFAULT_ADMIN_EMAIL:-admin@schemabio.local}
DEFAULT_ADMIN_PASSWORD=$DEFAULT_ADMIN_PASSWORD
EXTERNAL_AUTH_ENABLED=false
OVERLAY_ENABLED=false
EOF
  cat > /etc/schemabio/sepiida-agent.env <<EOF
SEPIIDA_SERVER_URL=http://127.0.0.1:${SEPIIDA_PORT:-9090}
SEPIIDA_AGENT_KEY=$SEPIIDA_AGENT_KEY
SEPIIDA_AGENT_ID=self-hosted-agent
SEPIIDA_AGENT_INTERVAL=60
SEPIIDA_WATCH_DIRS=$DATA_ROOT/output
SEPIIDA_ARCHIVE_URL=
EOF
  chmod 600 /etc/schemabio/octopus.env /etc/schemabio/sepiida-agent.env
}

write_health_waiter() {
  cat >"$INSTALL_ROOT/bin/wait-for-http" <<'EOF'
#!/bin/sh
set -eu
url="$1"
attempt=0
while [ "$attempt" -lt 60 ]; do
  if curl --fail --silent --show-error "$url" >/dev/null; then
    exit 0
  fi
  attempt=$((attempt + 1))
  sleep 2
done
echo "timed out waiting for $url" >&2
exit 1
EOF
  chmod 0755 "$INSTALL_ROOT/bin/wait-for-http"
}

write_systemd_units() {
  cat > /etc/systemd/system/schemabio-octopus.service <<EOF
[Unit]
Description=SchemaBio Octopus backend
Wants=network-online.target docker.service
After=network-online.target docker.service

[Service]
Type=simple
User=schemabio
Group=schemabio
SupplementaryGroups=docker
WorkingDirectory=$DATA_ROOT/output
EnvironmentFile=/etc/schemabio/octopus.env
ExecStartPre=$INSTALL_ROOT/bin/wait-for-http http://127.0.0.1:${SEPIIDA_PORT:-9090}/health
ExecStart=$INSTALL_ROOT/bin/octopus
Restart=on-failure
RestartSec=5s
NoNewPrivileges=true

[Install]
WantedBy=multi-user.target
EOF
  cat > /etc/systemd/system/schemabio-sepiida-agent.service <<EOF
[Unit]
Description=SchemaBio Sepiida Agent
Wants=network-online.target docker.service
After=network-online.target docker.service

[Service]
Type=simple
User=schemabio
Group=schemabio
SupplementaryGroups=docker
WorkingDirectory=$DATA_ROOT/output
EnvironmentFile=/etc/schemabio/sepiida-agent.env
ExecStartPre=$INSTALL_ROOT/bin/wait-for-http http://127.0.0.1:${SEPIIDA_PORT:-9090}/health
ExecStart=$INSTALL_ROOT/bin/sepiida-agent
Restart=on-failure
RestartSec=5s
NoNewPrivileges=true

[Install]
WantedBy=multi-user.target
EOF
  chmod 644 /etc/systemd/system/schemabio-octopus.service /etc/systemd/system/schemabio-sepiida-agent.service
}

install_host_services() {
  require_root
  require_command systemctl
  require_command useradd
  require_command usermod
  require_command runuser
  require_command getent
  require_command curl
  load_env
  resolve_paths

  if ! id schemabio >/dev/null 2>&1; then
    useradd --system --user-group --create-home --shell /usr/sbin/nologin schemabio
  fi
  getent group docker >/dev/null || die "Docker group does not exist"
  usermod -aG docker schemabio
  mkdir -p "$INSTALL_ROOT/bin" "$DATA_ROOT/output" "$DATA_ROOT/archive" "$DATA_ROOT/uploads"

  docker build -t schemabio/octopus-host:local "$DEPLOY_DIR/.."
  docker build -t schemabio/sepiida-agent-host:local -f "$DEPLOY_DIR/../../Sepiida/Dockerfile.agent" "$DEPLOY_DIR/../../Sepiida"
  extract_binary schemabio/octopus-host:local /app/octopus "$INSTALL_ROOT/bin/octopus"
  extract_binary schemabio/sepiida-agent-host:local /app/sepiida-agent "$INSTALL_ROOT/bin/sepiida-agent"
  write_health_waiter
  chown -R schemabio:schemabio "$INSTALL_ROOT" "$DATA_ROOT"

  runuser -u schemabio -- "$MINIWDL_PATH" --version >/dev/null
  runuser -u schemabio -- docker info >/dev/null
  write_host_environment
  write_systemd_units
  systemctl daemon-reload
  systemctl enable schemabio-octopus.service schemabio-sepiida-agent.service >/dev/null
}

show_credentials() {
  load_env
  printf 'Octopus administrator\n  email: %s\n  password: %s\n' "${DEFAULT_ADMIN_EMAIL:-admin@schemabio.local}" "$DEFAULT_ADMIN_PASSWORD"
}

command_name="${1:-}"
case "$command_name" in
  init)
    init_config
    ;;
  check)
    init_config
    check_config
    ;;
  install)
    init_config
    check_config
    install_host_services
    compose up -d --build
    systemctl start schemabio-octopus.service schemabio-sepiida-agent.service
    ;;
  up)
    require_root
    init_config
    check_config
    compose up -d
    systemctl start schemabio-octopus.service schemabio-sepiida-agent.service
    ;;
  down)
    require_root
    systemctl stop schemabio-sepiida-agent.service schemabio-octopus.service
    load_env
    compose down
    ;;
  status)
    load_env
    compose ps
    systemctl --no-pager status schemabio-octopus.service schemabio-sepiida-agent.service
    ;;
  credentials)
    show_credentials
    ;;
  *)
    printf 'Usage: %s init|check|install|up|down|status|credentials\n' "$0" >&2
    exit 2
    ;;
esac
